name: E2E Tests

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

env:
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
  PLAYWRIGHT_BROWSERS_PATH: 0
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:

      - name: Get Latest Release
        id: get_release
        run: |
          latest_release=$(curl -s https://api.github.com/repos/vercel/next.js/releases/latest | jq -r '.tag_name')
          echo "Latest release: $latest_release"
          echo "::set-output name=latest_release::$latest_release"

      - name: Get Previous Release
        id: get_previous_release
        run: echo "::set-output name=previous_release::$(cat previous_release.txt)"

      - name: Compare Releases
        id: compare_releases
        run: |
          latest_release="${{ steps.get_release.outputs.latest_release }}"
          previous_release="${{ steps.get_previous_release.outputs.previous_release }}"

          if [ "$latest_release" != "$previous_release" ]; then
            echo "Releases are different. Continuing the pipeline."
          else
            echo "Releases are the same. Exiting with success."
            exit 0
          fi

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::918074996169:role/GitHub
          aws-region: us-east-1

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up NodeJS v18
        uses: actions/setup-node@v3
        with:
          cache: pnpm # cache pnpm store
          node-version: 18.16.1

      - name: Install packages
        run: pnpm install

      - name: Get Playwright version
        id: playwright-version
        run: echo "version=$(npm ls @playwright/test | grep @playwright | sed 's/.*@//' | sed 's/ .*//' )"

      - name: Cache Playwright
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: "~/.cache/ms-playwright"
          key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install chromium --with-deps

      # Cache turbo runs
      - name: Cache Turbo
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      # Build all the packages
      - name: Build
        run: pnpm run build

      # Deploy e2e stage
      - name: Deploy NextjsSite
        working-directory: examples/sst
        run: npx sst deploy --stage e2e

      # Load app urls from .sst/output.json file
      - name: Set environments
        working-directory: examples/sst
        run: |
          APP_ROUTER_URL=$(jq -r '.["e2e-example-AppRouter"].url' .sst/outputs.json)
          echo "APP_ROUTER_URL=$APP_ROUTER_URL" >> $GITHUB_ENV
          PAGES_ROUTER_URL=$(jq -r '.["e2e-example-PagesRouter"].url' .sst/outputs.json)
          echo "PAGES_ROUTER_URL=$PAGES_ROUTER_URL" >> $GITHUB_ENV
          APP_PAGES_ROUTER_URL=$(jq -r '.["e2e-example-AppPagesRouter"].url' .sst/outputs.json)
          echo "APP_PAGES_ROUTER_URL=$APP_PAGES_ROUTER_URL" >> $GITHUB_ENV

      - name: Run e2e Test
        run: npm run e2e:test


      - name: Store Latest Release
        run: echo "${{ steps.get_release.outputs.latest_release }}" > previous_release.txt

      - name: Archive
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: sst
          path: |
            .sst/
            .next/
